theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev","play","next"]
on_collapsed_click = "spotify"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20
alert = 10

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = true
show_clocks = false

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "net"
format = "{speed_up;K*b} {speed_down;K*b}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
interval = "once"

